### ISSUE TITLE
Issue while running image on tekton CICD pipeline

### ISSUE THREAD

**Issue by narennadig** [bentoml/BentoML#1029]
OpenShift version: v3.11
K8 version: v1.11
Tekton Pipeline version: v0.12.1
Issue: Unable to run BentoML pipelines using tekton based CI/CD pipeline. The pipeline deploys the application pod however the sales app does not runs and shows the below error:
............................................................................................................................................................................................................

[2020-08-26 14:08:17 +0000] [17] [ERROR] **Exception in worker process**
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/conda/lib/python3.7/site-packages/bentoml/server/gunicorn_server.py", line 91, in load
    bento_service = load(self.bento_service_bundle_path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/saved_bundle/loader.py", line 199, in load
    svc_cls = load_bento_service_class(bundle_path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/saved_bundle/loader.py", line 119, in load_bento_service_class
    metadata["module_file"], bundle_path
bentoml.exceptions.BentoMLException: **Can not locate module_file holt_classifier.py in saved bundle /bento**
[2020-08-26 14:08:17 +0000] [17] [INFO] Worker exiting (pid: 17)
...........................................................................................................................................................................................................
Troubleshooting: We have tried running this same application using a docker image on local system and it runs perfectly fine. On CI/CD it fails, also validated the pod and found "/bento" and other files are copied correctly into the image while its being built by tekton. This does not appears to be an issue with the file not present as seen in the error, could be something related to BentoML based configuration in the pipeline config yaml. Appreciate any help to fix

**Comment by jiyer2016** [comment]
@narennadig  - Possible dupe of https://github.com/bentoml/BentoML/issues/1030
Did you build / package on windows and deploy on Linux ?

**Comment by narennadig** [comment]
@jiyer2016  Both on Linux..Did you find a solution???

**Comment by parano** [comment]
Hi @narennadig, could you try running the quick start example `IrisClassifier` in your environment and try building and running the generated docker image?

**Comment by narennadig** [comment]
@parano it is running on my local system without an issue

**Comment by parano** [comment]
Hey @narennadig, any progress after our last call? hope things are working now, let me know if there's still any issue with this

**Comment by narennadig** [comment]
@parano It works for iris example but not our time-series one..But do you think It's because I did "auto_pip_dependencies=["statsmodels == 0.10.1" ?

**Comment by parano** [comment]
@narennadig it's possible.

Try the following? 

```@env(auto_pip_dependencies=True, pip_dependencies=["statsmodels==0.10.1"])```

Be sure to remove the space in `"statsmodels == 0.10.1" `. The current released version of bentoml has an issue with parsing non-standard pypi package requirement. It has been fixed here and will not be a problem in future releases:  https://github.com/bentoml/BentoML/pull/1086

**Comment by narennadig** [comment]
@parano Just tried. it ...Still facing the issue ..when I added statsmodels==0.10.1 manually it worked(You can check our slack thread) ...Anyways..I'll be trying to run it on CICD after which we can close the issue if you want

**Comment by narennadig** [comment]
@parano It worked..I think that was the issue unfortunately....That requirements.txt getting populated issue still exists
